[package]
name = "usd-rs-tests"
version = "0.1.0"
authors = ["Luke Titley <from+usd_rs@luketitley.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usd = {path="../usd-rs", version="0.0.9"}
