[package]
name = "usd"
version = "0.0.9"
authors = ["Luke Titley <from+crates_io@luketitley.com>"]
edition = "2018"
license = "Apache-2.0"
description = "Rust bindings for USD"
repository = "https://github.com/luke-titley/usd-rs"
keywords = ["vfx", "graphics", "scene_description", "scene_graph", "alembic"]
documentation = "https://luke-titley.github.io/usd-rs/usd"

[package.metadata.docs.rs]
rustc-args = ["--cfg", "docsrs"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
usd-cpp = {path="../usd-cpp", version="0.1.1"} # We need this for the libs at link time
cpp = "0.5"
static_assertions = "1.1.0"
half = "1.6.0"
c_str_macro = "1.0.2"

[build-dependencies]
usd-cpp = {path="../usd-cpp", version="0.1.1"} # We need this for the headers at build time
cpp_build = "0.5"
fs_extra = "1.2.0"
