name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-20.04
    container:
      image: luketitley/vfxrs_env_usd:latest

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Run build
      run:
      - rustup default stable
      - env USD_ROOT=/usr/local/USD cargo build
    - name: Run test
      run: env USD_ROOT=/usr/local/USD LD_LIBRARY_PATH=/usr/local/USD/lib cargo test
    - name: Generate docs
      run:
      - env USD_ROOT=/usr/local/USD LD_LIBRARY_PATH=/usr/local/USD/lib cargo doc --no-deps
      - cp -r target/doc/* docs/

  # MacOS Disabled for now, see issue #2
  build-macos:
    if: ${{ false }}
    runs-on: macos-11

    steps:
    - uses: actions/checkout@v2
    - name: Init submodules
      run: git submodule update --init --recursive
    - name: Run build
      run: cargo build
